---
title: "Generative AI Misinformation Research"
subtitle: "STAT/DSDA 1010; Data Science and Society Using R"
author: Karissa Wong
format:
    revealjs:
        slide-number: true
        preview-links: true
        incremental: true
        theme: serif
---

# Overview

## Gen AI Misinformation Data
This project uses the [Gen AI Misinformation Detection Data (2024-2025)](https://www.kaggle.com/datasets/atharvasoundankar/gen-ai-misinformation-detection-datase-20242025) on Kaggle, which includes:

- Realistic simulations of news articles/social media posts labeled as potential AI-generated misinformation
- Time, location, author, attributes, credibility, and misinformation of each post

## Target Variables
For the purpose of this project, we will focus on the following variables:

- Country and city
- Token count
- Readability, sentiment, and toxicity score
- Model signature
- Engagement
- Misinformation

## Purpose
- Study the impact of Gen AI on misinformation in newswriting and social media
- Determine factors that cause text to be marked as AI writing
- Determine if AI produces more misinformation than humans
- How much engagement each post receives based on model signature

# Analysis

## Detected Misinformation Around the World
Some findings were:

- Not a significant difference in the number of GPT-like posts produced by each country
- Every post is produced in metropolitan areas, corresponding with current trend of larger cities adopting AI

## Engagement with Content
Some findings were:

- Overall, people engage with more human content (919,439 cases of engagement) than AI content (849,052 cases of engagement)
- Shows continuing dominance of human content in social media